<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>691c54a4-e57a-43ad-a5dc-2fe31dc7225a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Responses\" />
    <Folder Include="DTOs\Requests\" />
    <Folder Include="Helpers\" />
    <Folder Include="Services\Interfaces\" />
    <Folder Include="Settings\" />
  </ItemGroup>

</Project>
